import 'package:flutter/material.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLanguageCode = 'en';

  void setLanguage(String code) {
    _currentLanguageCode = code;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'home': 'Home',
      'search': 'Search',
      'messages': 'Messages',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'appearance': 'Appearance',
      'notifications': 'Notifications',
      'saved': 'Saved',
      'blocked': 'Blocked',
      'privacy': 'Privacy',
      'security': 'Security',
      'accessibility': 'Accessibility',
      'supervision': 'Supervision',
      'help': 'Help',
      'about': 'About',
      'logout': 'Log Out',
      'ghost_mode': 'Ghost Mode',
      'ghost_mode_subtitle': 'Browse without being seen',
      'welcome': 'Welcome',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'edit_profile': 'Edit Profile',
      'continue_text': 'Continue',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'search_languages': 'Search languages',
      'language_changed': 'Language changed to ',
      'how_you_use': 'How you use Skillze',
      'who_can_see': 'Who can see your content',
      'app_and_media': 'Your app and media',
      'families': 'For families',
      'more_info': 'More info and support',
      'for_you': 'For You',
      'following': 'Following',
      'discover': 'Discover',
      'skills': 'Skills',
      'roles': 'Roles',
      'filter': 'Filter',
      'range': 'Range',
      'unlimited': 'Unlimited',
      'apply': 'Apply',
      'reset': 'Reset',
      'active_now': 'Active Now',
      'repost': 'Repost',
      'not_interested': 'Not Interested',
      'follow': 'Follow',
      'unfollow': 'Unfollow',
      'hide': 'Hide',
      'about_this_account': 'About this account',
      'report_post': 'Report Post',
      'edit_post': 'Edit Post',
      'delete_post': 'Delete Post',
      'delete_post_confirm': 'Are you sure you want to delete this post?',
      'post_deleted_success': 'Post deleted successfully',
      'user_not_found': 'User not found',
      'date_joined': 'Date Joined',
      'unknown': 'Unknown',
      'account_based_in': 'Account Based In',
      'not_specified': 'Not Specified',
      'account_transparency': 'Account Transparency',
      'account_transparency_desc': 'Skillze is committed to showing you information about the accounts you interact with.',
      'about_account_privacy_notice': 'To help keep our community authentic, we’re showing information about accounts on Skillze. See why this information is important.',
    },
    'hi': {
      'home': 'होम',
      'search': 'खोजें',
      'messages': 'संदेश',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'appearance': 'दिखावट',
      'notifications': 'सूचनाएं',
      'saved': 'सहेजा गया',
      'blocked': 'अवरुद्ध',
      'privacy': 'गोपनीयता',
      'security': 'सुरक्षा',
      'accessibility': 'पहुंच',
      'supervision': 'पर्यवेक्षण',
      'help': 'सहायता',
      'about': 'बारे में',
      'logout': 'लॉग आउट',
      'ghost_mode': 'घोस्ट मोड',
      'ghost_mode_subtitle': 'बिना दिखे ब्राउज़ करें',
      'welcome': 'स्वागत है',
      'sign_in': 'साइन इन',
      'sign_up': 'साइन अप',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'continue_text': 'जारी रखें',
      'cancel': 'रद्द करें',
      'confirm': 'पुष्टि करें',
      'search_languages': 'भाषाएं खोजें',
      'language_changed': 'भाषा बदल दी गई है ',
      'how_you_use': 'आप Skillze का उपयोग कैसे करते हैं',
      'who_can_see': 'आपकी सामग्री कौन देख सकता है',
      'app_and_media': 'आपका ऐप और मीडिया',
      'families': 'परिवारों के लिए',
      'more_info': 'अधिक जानकारी और सहायता',
      'for_you': 'आपके लिए',
      'following': 'फ़ॉलो कर रहे हैं',
      'discover': 'खोजें',
      'skills': 'कौशल',
      'roles': 'भूमिकाएं',
      'filter': 'फ़िल्टर',
      'range': 'सीमा',
      'unlimited': 'असीमित',
      'apply': 'लागू करें',
      'reset': 'रीसेट करें',
      'active_now': 'अभी सक्रिय',
    },
    'te': {
      'home': 'హోమ్',
      'search': 'శోధన',
      'messages': 'సందేశాలు',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగులు',
      'language': 'భాష',
      'appearance': 'ప్రదర్శన',
      'notifications': 'నోటిఫికేషన్లు',
      'saved': 'సేవ్ చేయబడింది',
      'blocked': 'బ్లాక్ చేయబడింది',
      'privacy': 'గోప్యత',
      'security': 'భద్రత',
      'accessibility': 'యాక్సెసిబిలిటీ',
      'supervision': 'పర్యవేక్షణ',
      'help': 'సహాయం',
      'about': 'గురించి',
      'logout': 'లాగ్ అవుట్',
      'ghost_mode': 'ఘోస్ట్ మోడ్',
      'ghost_mode_subtitle': 'కనిపించకుండా బ్రౌజ్ చేయండి',
      'welcome': 'స్వాగతం',
      'sign_in': 'సైన్ ఇన్',
      'sign_up': 'సైన్ అప్',
      'edit_profile': 'ప్రొఫైల్ సవరించు',
      'continue_text': 'కొనసాగించు',
      'cancel': 'రద్దు',
      'confirm': 'నిర్ధారించు',
      'search_languages': 'భాషలను వెతకండి',
      'language_changed': 'భాష మార్చబడింది ',
      'how_you_use': 'మీరు Skillze ఎలా ఉపయోగిస్తారు',
      'who_can_see': 'మీ కంటెంట్‌ని ఎవరు చూడగలరు',
      'app_and_media': 'మీ యాప్ మరియు మీడియా',
      'families': 'కుటుంబాల కోసం',
      'more_info': 'మరింత సమాచారం మరియు మద్దతు',
      'for_you': 'మీ కోసం',
      'following': 'అనుసరిస్తున్నారు',
      'discover': 'కనుగొనండి',
      'skills': 'నైపుణ్యాలు',
      'roles': 'పాత్రలు',
      'filter': 'ఫిల్టర్',
      'range': 'పరిధి',
      'unlimited': 'అపరిమిత',
      'apply': 'వర్తింపజేయి',
      'reset': 'రీసెట్',
      'active_now': 'ప్రస్తుతం యాక్టివ్',
    },
    'es': {
      'home': 'Inicio',
      'search': 'Buscar',
      'messages': 'Mensajes',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'appearance': 'Apariencia',
      'notifications': 'Notificaciones',
      'saved': 'Guardado',
      'blocked': 'Bloqueado',
      'privacy': 'Privacidad',
      'security': 'Seguridad',
      'accessibility': 'Accesibilidad',
      'supervision': 'Supervisión',
      'help': 'Ayuda',
      'about': 'Acerca de',
      'logout': 'Cerrar sesión',
      'ghost_mode': 'Modo Fantasma',
      'ghost_mode_subtitle': 'Navega sin ser visto',
      'welcome': 'Bienvenido',
      'sign_in': 'Iniciar sesión',
      'sign_up': 'Registrarse',
      'edit_profile': 'Editar perfil',
      'continue_text': 'Continuar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'search_languages': 'Buscar idiomas',
      'language_changed': 'Idioma cambiado a ',
      'how_you_use': 'Cómo usas Skillze',
      'who_can_see': 'Quién puede ver tu contenido',
      'app_and_media': 'Tu aplicación y medios',
      'families': 'Para familias',
      'more_info': 'Más información y soporte',
      'for_you': 'Para ti',
      'following': 'Siguiendo',
      'discover': 'Descubrir',
      'skills': 'Habilidades',
      'roles': 'Roles',
      'filter': 'Filtrar',
      'range': 'Rango',
      'unlimited': 'Ilimitado',
      'apply': 'Aplicar',
      'reset': 'Reiniciar',
      'active_now': 'Activo ahora',
    },
    'fr': {
      'home': 'Accueil',
      'search': 'Recherche',
      'messages': 'Messages',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'language': 'Langue',
      'appearance': 'Apparence',
      'notifications': 'Notifications',
      'saved': 'Enregistré',
      'blocked': 'Bloqué',
      'privacy': 'Confidentialité',
      'security': 'Sécurité',
      'accessibility': 'Accessibilité',
      'supervision': 'Supervision',
      'help': 'Aide',
      'about': 'À propos',
      'logout': 'Déconnexion',
      'ghost_mode': 'Mode Fantôme',
      'ghost_mode_subtitle': 'Naviguer sans être vu',
      'welcome': 'Bienvenue',
      'sign_in': 'Se connecter',
      'sign_up': 'S\'inscrire',
      'edit_profile': 'Modifier le profil',
      'continue_text': 'Continuer',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'search_languages': 'Rechercher des langues',
      'language_changed': 'Langue changée en ',
      'how_you_use': 'Comment vous utilisez Skillze',
      'who_can_see': 'Qui peut voir votre contenu',
      'app_and_media': 'Votre application et vos médias',
      'families': 'Pour les familles',
      'more_info': 'Plus d\'infos et support',
      'for_you': 'Pour vous',
      'following': 'Abonnements',
      'discover': 'Découvrir',
      'skills': 'Compétences',
      'roles': 'Rôles',
      'filter': 'Filtrer',
      'range': 'Portée',
      'unlimited': 'Illimité',
      'apply': 'Appliquer',
      'reset': 'Réinitialiser',
      'active_now': 'En ligne',
    },
    'de': {
      'home': 'Startseite',
      'search': 'Suche',
      'messages': 'Nachrichten',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'appearance': 'Aussehen',
      'notifications': 'Benachrichtigungen',
      'saved': 'Gespeichert',
      'blocked': 'Blockiert',
      'privacy': 'Datenschutz',
      'security': 'Sicherheit',
      'accessibility': 'Barrierefreiheit',
      'supervision': 'Aufsicht',
      'help': 'Hilfe',
      'about': 'Über',
      'logout': 'Abmelden',
      'ghost_mode': 'Geistermodus',
      'ghost_mode_subtitle': 'Surfen, ohne gesehen zu werden',
      'welcome': 'Willkommen',
      'sign_in': 'Anmelden',
      'sign_up': 'Registrieren',
      'edit_profile': 'Profil bearbeiten',
      'continue_text': 'Weiter',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'search_languages': 'Sprachen suchen',
      'language_changed': 'Sprache geändert auf ',
      'how_you_use': 'Wie du Skillze nutzt',
      'who_can_see': 'Wer deine Inhalte sehen kann',
      'app_and_media': 'Deine App und Medien',
      'families': 'Für Familien',
      'more_info': 'Weitere Infos und Support',
      'for_you': 'Für dich',
      'following': 'Gefolgt',
      'discover': 'Entdecken',
      'skills': 'Fähigkeiten',
      'roles': 'Rollen',
      'filter': 'Filtern',
      'range': 'Bereich',
      'unlimited': 'Unbegrenzt',
      'apply': 'Anwenden',
      'reset': 'Zurücksetzen',
      'active_now': 'Jetzt aktiv',
    },
  };

  String translate(String key) {
    return _translations[_currentLanguageCode]?[key] ?? _translations['en']?[key] ?? key;
  }
}

extension LocalizationExtension on BuildContext {
  String t(String key) => LocalizationService().translate(key);
}
