// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbj1g-gkr6HsFmLfGrfyj8EbTwDdNPxQ0',
    appId: '1:536909553761:web:275f9f88fabd505b4e8a20',
    messagingSenderId: '536909553761',
    projectId: 'feed-609dd',
    authDomain: 'feed-609dd.firebaseapp.com',
    storageBucket: 'feed-609dd.firebasestorage.app',
    measurementId: 'G-KV46ETPZ2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNK28Lqfjb9Cq5MIWXPHg2vy0zHUbg2jI',
    appId: '1:536909553761:android:c5a48bd6eb55400d4e8a20',
    messagingSenderId: '536909553761',
    projectId: 'feed-609dd',
    storageBucket: 'feed-609dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHHXzArbxMW8KPrPaxdstBHakuJdr8MiA',
    appId: '1:536909553761:ios:8a8e0633b9a49b0f4e8a20',
    messagingSenderId: '536909553761',
    projectId: 'feed-609dd',
    storageBucket: 'feed-609dd.firebasestorage.app',
    androidClientId:
        '536909553761-50ta4ar22dgugcjuk214tksnrvrardjc.apps.googleusercontent.com',
    iosClientId:
        '536909553761-gmvapt0cfh67vlj0b7qr033asde003tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHHXzArbxMW8KPrPaxdstBHakuJdr8MiA',
    appId: '1:536909553761:ios:8a8e0633b9a49b0f4e8a20',
    messagingSenderId: '536909553761',
    projectId: 'feed-609dd',
    storageBucket: 'feed-609dd.firebasestorage.app',
    androidClientId:
        '536909553761-50ta4ar22dgugcjuk214tksnrvrardjc.apps.googleusercontent.com',
    iosClientId:
        '536909553761-gmvapt0cfh67vlj0b7qr033asde003tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbj1g-gkr6HsFmLfGrfyj8EbTwDdNPxQ0',
    appId: '1:536909553761:web:4a909111a59470454e8a20',
    messagingSenderId: '536909553761',
    projectId: 'feed-609dd',
    authDomain: 'feed-609dd.firebaseapp.com',
    storageBucket: 'feed-609dd.firebasestorage.app',
    measurementId: 'G-F2BH6EB6YL',
  );
}
